name: Build iOS Simulator App for Appetize

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-ios-sim:
    runs-on: macos-15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          
      - name: Install dependencies
        run: npm ci

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Prebuild iOS project
        run: npx expo prebuild --platform ios --no-install

      - name: Install iOS native dependencies
        run: |
          cd ios
          pod install

      - name: Build .app for simulator
        run: |
          xcodebuild \
            -workspace ios/*.xcworkspace \
            -scheme $(xcodebuild -list -workspace ios/*.xcworkspace | awk '/Schemes:/,/^\s*$/' | tail -n +2 | head -1 | xargs) \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build

      - name: Zip the .app
        run: |
          APP_PATH=$(find build/Build/Products/Debug-iphonesimulator -name "*.app" | head -1)
          echo "App path: $APP_PATH"
          cd $(dirname "$APP_PATH")
          zip -r $GITHUB_WORKSPACE/app.zip $(basename "$APP_PATH")

      - name: Upload Appetize Artifact
        uses: actions/upload-artifact@v4
        with:
          name: appetize-ios-simulator
          path: app.zip
