name: Build iOS Simulator App for Appetize

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-ios-sim:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Prebuild iOS project
        run: npx expo prebuild --platform ios

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build for iOS Simulator
        run: |
          xcodebuild \
            -workspace ios/gomatodo.xcworkspace \
            -scheme gomatodo \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath ios_build

      - name: Zip .app
        run: |
          cd ios_build/Build/Products/Debug-iphonesimulator
          zip -r gomatodo.zip gomatodo.app
          mv gomatodo.zip $GITHUB_WORKSPACE

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-appetize
          path: gomatodo.zip
