name: Build iOS Simulator App for Appetize

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build-ios-sim:
    runs-on: macos-15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Prebuild iOS project
        run: npx expo prebuild --platform ios

      - name: Build iOS app
        run: |
          mkdir -p build
          eas build --platform ios --local --profile simulator --output build/app.app

      - name: Zip the .app bundle
        run: |
          cd build
          zip -r app.zip app.app

      - name: Upload Appetize Artifact
        uses: actions/upload-artifact@v4
        with:
          name: appetize-ios-simulator
          path: build/app.zip
